### ISSUE TITLE
paper request

### ISSUE THREAD

**Issue by ctbulhc** [khawar-islam/diffuseMix#1]
**Dear islam,
 What time will you release your CVPR2024 paper "DiffuseMix: Label-Preserving Data Augmentation with Diffusion Models"**
 **It`s a intresting work, and i really want to read it!**

**Comment by diffuseMix** [comment]
Dear @ctbulhc 

Thanks for your interest. I have already submitted into arXiv and maybe it will available soon and i will post the link there

**Comment by ctbulhc** [comment]
Dear islam,
Thanks your swift answer.
