### ISSUE TITLE
Medical image prompt words

### ISSUE THREAD

**Issue by T1ROSE** [khawar-islam/diffuseMix#11]
Hi, great work. I have a small question, now I want to apply DiffuseMix to medical images, but I have a hard time with the text hint selection. Do you have any suggestions here?

**Comment by khawar-islam** [comment]
Dear @T1ROSE 

Thanks for reaching out. I do not have any idea for medical images but I would love to help you. Would it be possible for you to show some sample medical images ? Then, I will design some prompts and let you know.

**Comment by T1ROSE** [comment]
Thanks for the quick response! Here are some sample medical images.
![benign (2)](https://github.com/user-attachments/assets/ffc031bb-c0e0-4de4-acf7-e240471d9811)
![benign (13)](https://github.com/user-attachments/assets/dae9db04-aedb-4a76-88ff-90d049fb75fb)
![COVID (2)](https://github.com/user-attachments/assets/fd26111a-3089-4c13-99c3-397b2403a6ec)
![COVID (13)](https://github.com/user-attachments/assets/6ad2af6b-ef24-4d50-a312-b067e0e3632d)
![SARS (21)](https://github.com/user-attachments/assets/6b5328c3-44bc-4dcf-8970-045e3613b973)
I would appreciate your help in coming up with some suitable prompt words.

**Comment by khawar-islam** [comment]
@T1ROSE thanks, i will think about it as these images are far from our task and images are entirely different.
