### ISSUE TITLE
Table 17: safety metrics

### ISSUE THREAD

**Issue by ahmadmughees** [khawar-islam/diffuseMix#12]
Hey @khawar-islam, 

Interesting and exciting paper. I am just trying to reproduce your results and wondering how you evaluated safety metrics and created Table 17. [IPmix](https://github.com/hzlsaber/IPMix/tree/main) and [pixmix](https://github.com/andyzoujm/pixmix) only provide code to compute mean corruption error and adversarial test error. 

Can you provide code to the compute rest of the metrics as well? 

Thanks.

**Comment by khawar-islam** [comment]
Hi @ahmadmughees 

I am very sorry for very late reply. Actually, I was highly occupied in full-time job and research, as, I remember that I got these metrics code from AugMix issue section where they mention the link of the code.

Apologizes for very late reply.
