### ISSUE TITLE
Augmentation for Object Detection

### ISSUE THREAD

**Issue by ylchao** [khawar-islam/diffuseMix#2]
Can I use diffusemix for object detection? Have you investigated this line of work? Thank you

**Comment by khawar-islam** [comment]
@ylchao thank you for your question, no i didn't check for the object detection maybe in future i will investigate it

**Comment by suunnnnnj** [comment]
@ylchao 

hello. I've been testing on object detection.
And this augmentation method gave me really amazing results.
I was able to find a lot of evidence of robustness in my work.

Thanks for your great work. @khawar-islam

**Comment by khawar-islam** [comment]
thank you very much @suunnnnnj  looking forward for your work.
