### ISSUE TITLE
Ask for generated Images and train.py 

### ISSUE THREAD

**Issue by roy-ch** [khawar-islam/diffuseMix#4]
I'm very appreciate your work!
I am currently conducting research in the same area and am very impressed by your results.
To facilitate a fair comparison in my experiments, I would be grateful if you could share the generated images and training scripts used in your study.

**Comment by khawar-islam** [comment]
Dear @roy-ch 

Thanks for your email. You can generate images via our code but remember that it depends on dataset length, bigger length takes  long time. Also, I have shared the training code of https://github.com/khawar-islam/Stanford-Cars dataset. You can run and reproduce the results.
