### ISSUE TITLE
提示词只能用readme给定的那些吗

### ISSUE THREAD

**Issue by Wyatt823** [khawar-islam/diffuseMix#5]
你好！感谢您的工作！
我想问一下在增强图像时，提示词只能用readme中给的的那一系列吗？

**Comment by khawar-islam** [comment]
Hello @Kris0823 

Yes, you can use the prompts given in readme, just try to use 1 to 2 prompts first and check the accuracy and then go for additional prompts.

**Comment by 7ywx** [comment]
Can prompt words not in the prompt word list be tried?

**Comment by khawar-islam** [comment]
@7ywx you can try some new prompt words and check the visual results. We introduce filter like prompts which can change image visually and preserve semantic information of image,
