### ISSUE TITLE
The number of prompts to get satisfactory results

### ISSUE THREAD

**Issue by Petershen-csworld** [khawar-islam/diffuseMix#8]
Thank you for your impressive work! It is so helpful and elegant!
I am recently trying to apply this work on relevant downstream tasks. I note that you get an error rate of **17.38** on CIFAR100 dataset, which is pretty cool.
I tried to use 3 prompts as a start point, but failed to get result good enough to beat the one training on the original dataset. I wonder how many prompts should be used to attain comparable results to your experiments (on CIFAR100)😉. Much thanks!

**Comment by khawar-islam** [comment]
Dear @Petershen-csworld 

Thanks for your question, can you show some images? On CIFAR-100, I will recommend you to first upscale the images and then feed into the diffuseMix, it really helps you in image generation process. Regarding the number of prompt, i need to check from the log file and let you know, it is in my cloud sever so you need to wait for it

**Comment by Petershen-csworld** [comment]
Thank you for your quick response!  Here are some pictures generated using prompt "aurora", "autumn", "mosaic", "snowy", respectively. 
![2_prompt_aurora](https://github.com/user-attachments/assets/4d6a2c82-0251-4387-acc9-72131baa793e)
![2_prompt_autumn](https://github.com/user-attachments/assets/a0ec0d3f-b9e0-42eb-bf9b-4b1346c674cc)
![2_prompt_mosaic](https://github.com/user-attachments/assets/fd09bca4-cdb3-4c86-8575-2d0f1f798580)
![2_prompt_snowy](https://github.com/user-attachments/assets/36473af0-43b8-47c8-aef6-4bdbb0b361db)
During the generation process, I rescaled the original images to resolution **256x256** then fed it into the pipeline.

**Comment by khawar-islam** [comment]
can you show me the 256x256 image? you first need to upscale the image and then feed into the diffuseMix pipeline then it will generate more consistent image.

**Comment by Petershen-csworld** [comment]
Certainly! Maybe I need to do something like **super resolution** first instead of simply resizing it? Here are some images sampled from my results.
![0](https://github.com/user-attachments/assets/54cfe704-b77c-4c30-9b6b-249b0936d203) 
*original*
![0_prompt_autumn](https://github.com/user-attachments/assets/a7f49110-468d-4e76-ba7f-8126d6f86710)
*prompt: autumn*
![0_prompt_mosaic](https://github.com/user-attachments/assets/f80a9558-4382-4783-bba7-5cbb179d1b08)
*prompt: mosaic*
![0_prompt_snowy](https://github.com/user-attachments/assets/b44978b9-db2f-48b9-84aa-4b36353531d5)
*prompt: snowy*
![0_prompt_watercolor art](https://github.com/user-attachments/assets/f2040b9a-4541-4347-bcda-3fc95251e6a5)
*prompt: watercolor art*

**Comment by khawar-islam** [comment]
Yes, you have to do the super resolution first then you will feed into the diffuseMix, this is only in the case of CIFAR, you can also explore the cars and flower102 dataset to check the prompts results where you do not need to super resolution.
